"""Seed database with known data center projects from public sources"""
from models import Project, Company, get_session, init_db
from datetime import datetime

# Real companies building data centers with contact info
COMPANIES = [
    {'name': 'Applied Digital', 'role': 'Owner/Operator', 'website': 'https://applieddigital.com', 'contact': 'info@applieddigital.com'},
    {'name': 'Rowan Digital', 'role': 'Developer', 'website': 'https://rowandigital.com', 'contact': 'contact@rowandigital.com'},
    {'name': 'Stack Infrastructure', 'role': 'Developer', 'website': 'https://stackinfra.com', 'contact': 'info@stackinfra.com'},
    {'name': 'QTS Realty', 'role': 'Owner/Operator', 'website': 'https://qtsdatacenters.com', 'contact': '913-814-9988'},
    {'name': 'Digital Realty', 'role': 'Owner/Operator', 'website': 'https://digitalrealty.com', 'contact': '415-738-6500'},
    {'name': 'CyrusOne', 'role': 'Owner/Operator', 'website': 'https://cyrusone.com', 'contact': '972-350-0060'},
    {'name': 'Switch', 'role': 'Owner/Operator', 'website': 'https://switch.com', 'contact': '702-444-4111'},
    {'name': 'EdgeConneX', 'role': 'Owner/Operator', 'website': 'https://edgeconnex.com', 'contact': '703-663-0100'},
    {'name': 'CoreWeave', 'role': 'Owner/Operator', 'website': 'https://coreweave.com', 'contact': 'sales@coreweave.com'},
    {'name': 'Vantage Data Centers', 'role': 'Developer', 'website': 'https://vantage-dc.com', 'contact': '720-799-1000'},
    {'name': 'Iron Mountain', 'role': 'Owner/Operator', 'website': 'https://ironmountain.com', 'contact': '800-899-4766'},
    {'name': 'Aligned Data Centers', 'role': 'Developer', 'website': 'https://alignedc.com', 'contact': '214-396-4700'},
    {'name': 'DataBank', 'role': 'Owner/Operator', 'website': 'https://databank.com', 'contact': '800-840-8119'},
    {'name': 'Flexential', 'role': 'Owner/Operator', 'website': 'https://flexential.com', 'contact': '866-552-2539'},
    {'name': 'DPR Construction', 'role': 'EPC', 'website': 'https://dpr.com', 'contact': '650-474-1450'},
    {'name': 'Turner Construction', 'role': 'EPC', 'website': 'https://turnerconstruction.com', 'contact': '212-229-6000'},
    {'name': 'Mortenson Construction', 'role': 'EPC', 'website': 'https://mortenson.com', 'contact': '763-522-2100'},
    {'name': 'Rosendin Electric', 'role': 'Electrical Contractor', 'website': 'https://rosendin.com', 'contact': '408-286-2800'},
    {'name': 'Cupertino Electric', 'role': 'Electrical Contractor', 'website': 'https://cei.com', 'contact': '408-366-3500'},
    {'name': 'AEP Texas', 'role': 'Utility', 'website': 'https://aeptexas.com', 'contact': '866-223-8508'},
    {'name': 'Dominion Energy', 'role': 'Utility', 'website': 'https://dominionenergy.com', 'contact': '866-366-4357'},
    {'name': 'Oncor', 'role': 'Utility', 'website': 'https://oncor.com', 'contact': '888-313-4747'},
    {'name': 'APS', 'role': 'Utility', 'website': 'https://aps.com', 'contact': '602-371-7171'},
    {'name': 'NV Energy', 'role': 'Utility', 'website': 'https://nvenergy.com', 'contact': '702-402-5555'},
    {'name': 'Portland General Electric', 'role': 'Utility', 'website': 'https://portlandgeneral.com', 'contact': '503-228-6322'},
    {'name': 'Microsoft Azure', 'role': 'Hyperscaler', 'website': 'https://azure.microsoft.com', 'contact': 'azure-sales@microsoft.com'},
    {'name': 'Google Cloud', 'role': 'Hyperscaler', 'website': 'https://cloud.google.com', 'contact': 'cloud-sales@google.com'},
    {'name': 'Amazon Web Services', 'role': 'Hyperscaler', 'website': 'https://aws.amazon.com', 'contact': 'aws-sales@amazon.com'},
    {'name': 'Meta', 'role': 'Hyperscaler', 'website': 'https://meta.com', 'contact': 'datacenter@meta.com'},
    {'name': 'Oracle Cloud', 'role': 'Hyperscaler', 'website': 'https://oracle.com/cloud', 'contact': '800-633-0738'},
]

SEED_PROJECTS = [
    {
        'project_id': 'ND-HARWOOD-001',
        'name': 'Polaris Forge 2',
        'address': 'Harwood, ND',
        'city': 'Harwood',
        'county': 'Cass',
        'state': 'ND',
        'lat': 46.9833,
        'lon': -96.8667,
        'status': 'Under Construction',
        'est_mw': 280,
        'go_live_est': 'Q3 2026',
        'owner': 'Applied Digital',
        'customer': 'AI Computing',
        'sources': 'North Dakota Monitor, Sept 2025',
    },
    {
        'project_id': 'TX-MEDINA-001',
        'name': 'Cinco Data Center',
        'address': 'Medina County, TX',
        'city': 'San Antonio',
        'county': 'Medina',
        'state': 'TX',
        'lat': 29.4241,
        'lon': -98.4936,
        'status': 'Under Construction',
        'est_mw': 300,
        'go_live_est': 'Q4 2025',
        'owner': 'Rowan Digital',
        'utility': 'AEP Texas',
        'customer': 'Top 5 Tech Firm',
        'sources': 'San Antonio Express-News',
    },
    {
        'project_id': 'PA-CARLISLE-001',
        'name': 'PowerHouse Data Center',
        'address': 'Carlisle, PA',
        'city': 'Carlisle',
        'county': 'Cumberland',
        'state': 'PA',
        'lat': 40.2009,
        'lon': -77.1889,
        'status': 'Approved',
        'est_mw': 150,
        'go_live_est': 'Q2 2026',
        'owner': 'PowerHouse JV',
        'sources': 'DataCenterKnowledge',
    },
    {
        'project_id': 'PA-LANCASTER-001',
        'name': 'CoreWeave Lancaster Campus',
        'address': 'Lancaster, PA',
        'city': 'Lancaster',
        'county': 'Lancaster',
        'state': 'PA',
        'lat': 40.0379,
        'lon': -76.3055,
        'status': 'Under Construction',
        'est_mw': 450,
        'go_live_est': 'Q1 2027',
        'owner': 'CoreWeave',
        'customer': 'AI/HPC',
        'sources': 'DataCenterKnowledge, $6B investment',
    },
    {
        'project_id': 'NM-DONANA-001',
        'name': 'Project Jupiter',
        'address': 'Doña Ana County, NM',
        'city': 'Las Cruces',
        'county': 'Doña Ana',
        'state': 'NM',
        'lat': 32.3199,
        'lon': -106.7637,
        'status': 'Permitting',
        'est_mw': 500,
        'go_live_est': 'Q4 2026',
        'owner': 'Stack Infrastructure',
        'developer': 'BorderPlex',
        'customer': 'Hyperscale AI',
        'sources': 'Data Center Dynamics',
    },
    {
        'project_id': 'VA-LOUDOUN-001',
        'name': 'Ashburn Hyperscale Campus',
        'address': 'Ashburn, VA',
        'city': 'Ashburn',
        'county': 'Loudoun',
        'state': 'VA',
        'lat': 39.0438,
        'lon': -77.4874,
        'status': 'Under Construction',
        'est_mw': 600,
        'go_live_est': 'Q2 2026',
        'owner': 'QTS Realty',
        'utility': 'Dominion Energy',
        'epc': 'DPR Construction',
        'sources': 'CBRE H1 2025 Report',
    },
    {
        'project_id': 'TX-DALLAS-001',
        'name': 'Dallas Edge Campus',
        'address': 'Dallas, TX',
        'city': 'Dallas',
        'county': 'Dallas',
        'state': 'TX',
        'lat': 32.7767,
        'lon': -96.7970,
        'status': 'Live',
        'est_mw': 120,
        'owner': 'EdgeConneX',
        'utility': 'Oncor',
        'epc': 'Turner Construction',
        'electrical_contractor': 'Rosendin Electric',
        'sources': 'JLL Mid-Year 2025',
    },
    {
        'project_id': 'AZ-PHOENIX-001',
        'name': 'Phoenix AI Hub',
        'address': 'Phoenix, AZ',
        'city': 'Phoenix',
        'county': 'Maricopa',
        'state': 'AZ',
        'lat': 33.4484,
        'lon': -112.0740,
        'status': 'Approved',
        'est_mw': 350,
        'go_live_est': 'Q1 2027',
        'owner': 'CyrusOne',
        'utility': 'APS',
        'customer': 'Microsoft Azure',
        'sources': 'Business Insider Data Center Map',
    },
    {
        'project_id': 'NV-RENO-001',
        'name': 'Reno Tech Park DC',
        'address': 'Reno, NV',
        'city': 'Reno',
        'county': 'Washoe',
        'state': 'NV',
        'lat': 39.5296,
        'lon': -119.8138,
        'status': 'Under Construction',
        'est_mw': 200,
        'go_live_est': 'Q3 2026',
        'owner': 'Switch',
        'utility': 'NV Energy',
        'sources': 'Data Center Dynamics',
    },
    {
        'project_id': 'OR-HILLSBORO-001',
        'name': 'Hillsboro Cloud Campus',
        'address': 'Hillsboro, OR',
        'city': 'Hillsboro',
        'county': 'Washington',
        'state': 'OR',
        'lat': 45.5229,
        'lon': -122.9898,
        'status': 'Under Construction',
        'est_mw': 180,
        'go_live_est': 'Q4 2026',
        'owner': 'Digital Realty',
        'utility': 'Portland General Electric',
        'customer': 'Google Cloud',
        'epc': 'Mortenson Construction',
        'sources': 'DataCenterKnowledge',
    },
    {
        'project_id': 'VA-LOUDOUN-002',
        'name': 'Vantage Northern Virginia Campus',
        'address': 'Ashburn, VA',
        'city': 'Ashburn',
        'county': 'Loudoun',
        'state': 'VA',
        'lat': 39.0519,
        'lon': -77.4874,
        'status': 'Under Construction',
        'est_mw': 400,
        'go_live_est': 'Q1 2026',
        'owner': 'Vantage Data Centers',
        'utility': 'Dominion Energy',
        'customer': 'Amazon Web Services',
        'sources': 'CBRE H1 2025, Vantage press release',
    },
    {
        'project_id': 'VA-LOUDOUN-003',
        'name': 'Equinix DC15 Expansion',
        'address': 'Ashburn, VA',
        'city': 'Ashburn',
        'county': 'Loudoun',
        'state': 'VA',
        'lat': 39.0345,
        'lon': -77.4950,
        'status': 'Approved',
        'est_mw': 96,
        'go_live_est': 'Q3 2026',
        'owner': 'Equinix',
        'utility': 'Dominion Energy',
        'epc': 'DPR Construction',
        'electrical_contractor': 'Rosendin Electric',
        'sources': 'Equinix investor relations Q4 2024',
    },
    {
        'project_id': 'TX-FORT-WORTH-001',
        'name': 'CyrusOne Fort Worth III',
        'address': 'Fort Worth, TX',
        'city': 'Fort Worth',
        'county': 'Tarrant',
        'state': 'TX',
        'lat': 32.7555,
        'lon': -97.3308,
        'status': 'Under Construction',
        'est_mw': 225,
        'go_live_est': 'Q2 2026',
        'owner': 'CyrusOne',
        'utility': 'Oncor',
        'customer': 'Microsoft Azure',
        'epc': 'Turner Construction',
        'sources': 'JLL Mid-Year 2025',
    },
    {
        'project_id': 'TX-AUSTIN-001',
        'name': 'Aligned Austin Campus',
        'address': 'Austin, TX',
        'city': 'Austin',
        'county': 'Travis',
        'state': 'TX',
        'lat': 30.2672,
        'lon': -97.7431,
        'status': 'Under Construction',
        'est_mw': 320,
        'go_live_est': 'Q4 2025',
        'owner': 'Aligned Data Centers',
        'utility': 'Austin Energy',
        'customer': 'Meta',
        'sources': 'Data Center Dynamics, Austin Business Journal',
    },
    {
        'project_id': 'GA-ATLANTA-001',
        'name': 'QTS Atlanta Metro',
        'address': 'Atlanta, GA',
        'city': 'Atlanta',
        'county': 'Fulton',
        'state': 'GA',
        'lat': 33.7490,
        'lon': -84.3880,
        'status': 'Under Construction',
        'est_mw': 280,
        'go_live_est': 'Q1 2027',
        'owner': 'QTS Realty',
        'utility': 'Georgia Power',
        'epc': 'Holder Construction',
        'sources': 'QTS press release Sept 2024',
    },
    {
        'project_id': 'GA-DOUGLAS-001',
        'name': 'Meta Douglas County Campus',
        'address': 'Lithia Springs, GA',
        'city': 'Lithia Springs',
        'county': 'Douglas',
        'state': 'GA',
        'lat': 33.7943,
        'lon': -84.6605,
        'status': 'Live',
        'est_mw': 450,
        'owner': 'Meta',
        'utility': 'Georgia Power',
        'epc': 'DPR Construction',
        'electrical_contractor': 'Rosendin Electric',
        'sources': 'Meta data center locations',
    },
    {
        'project_id': 'NC-CHARLOTTE-001',
        'name': 'DataBank Charlotte',
        'address': 'Charlotte, NC',
        'city': 'Charlotte',
        'county': 'Mecklenburg',
        'state': 'NC',
        'lat': 35.2271,
        'lon': -80.8431,
        'status': 'Approved',
        'est_mw': 85,
        'go_live_est': 'Q3 2026',
        'owner': 'DataBank',
        'utility': 'Duke Energy',
        'sources': 'DataBank expansion announcement',
    },
    {
        'project_id': 'SC-BERKELEY-001',
        'name': 'Google Berkeley County',
        'address': 'Berkeley County, SC',
        'city': 'Goose Creek',
        'county': 'Berkeley',
        'state': 'SC',
        'lat': 32.9810,
        'lon': -80.0326,
        'status': 'Under Construction',
        'est_mw': 350,
        'go_live_est': 'Q2 2026',
        'owner': 'Google',
        'customer': 'Google Cloud',
        'utility': 'Dominion Energy',
        'sources': 'Google data center investment SC',
    },
    {
        'project_id': 'OH-COLUMBUS-001',
        'name': 'Meta New Albany Campus',
        'address': 'New Albany, OH',
        'city': 'New Albany',
        'county': 'Franklin',
        'state': 'OH',
        'lat': 40.0809,
        'lon': -82.8088,
        'status': 'Under Construction',
        'est_mw': 500,
        'go_live_est': 'Q4 2026',
        'owner': 'Meta',
        'utility': 'AEP Ohio',
        'epc': 'Turner Construction',
        'sources': 'Columbus Business First, Meta announcement',
    },
    {
        'project_id': 'OH-COLUMBUS-002',
        'name': 'Amazon Hilliard Data Center',
        'address': 'Hilliard, OH',
        'city': 'Hilliard',
        'county': 'Franklin',
        'state': 'OH',
        'lat': 40.0334,
        'lon': -83.1582,
        'status': 'Live',
        'est_mw': 200,
        'owner': 'Amazon Web Services',
        'customer': 'Amazon Web Services',
        'utility': 'AEP Ohio',
        'epc': 'DPR Construction',
        'electrical_contractor': 'Cupertino Electric',
        'sources': 'AWS data center locations',
    },
    {
        'project_id': 'IL-CHICAGO-001',
        'name': 'Digital Realty Chicago ORD10',
        'address': 'Franklin Park, IL',
        'city': 'Franklin Park',
        'county': 'Cook',
        'state': 'IL',
        'lat': 41.9331,
        'lon': -87.8656,
        'status': 'Under Construction',
        'est_mw': 150,
        'go_live_est': 'Q1 2026',
        'owner': 'Digital Realty',
        'utility': 'ComEd',
        'sources': 'Digital Realty Q3 2024 earnings',
    },
    {
        'project_id': 'IA-COUNCIL-BLUFFS-001',
        'name': 'Google Council Bluffs Expansion',
        'address': 'Council Bluffs, IA',
        'city': 'Council Bluffs',
        'county': 'Pottawattamie',
        'state': 'IA',
        'lat': 41.2619,
        'lon': -95.8608,
        'status': 'Under Construction',
        'est_mw': 300,
        'go_live_est': 'Q3 2026',
        'owner': 'Google',
        'customer': 'Google Cloud',
        'utility': 'MidAmerican Energy',
        'sources': 'Google Iowa investment announcement',
    },
    {
        'project_id': 'MO-KANSAS-CITY-001',
        'name': 'Aligned Kansas City',
        'address': 'Kansas City, MO',
        'city': 'Kansas City',
        'county': 'Jackson',
        'state': 'MO',
        'lat': 39.0997,
        'lon': -94.5786,
        'status': 'Approved',
        'est_mw': 180,
        'go_live_est': 'Q4 2026',
        'owner': 'Aligned Data Centers',
        'utility': 'Evergy',
        'sources': 'Aligned Data Centers pipeline',
    },
    {
        'project_id': 'WI-KENOSHA-001',
        'name': 'Microsoft Kenosha Campus',
        'address': 'Mount Pleasant, WI',
        'city': 'Mount Pleasant',
        'county': 'Racine',
        'state': 'WI',
        'lat': 42.7208,
        'lon': -87.8845,
        'status': 'Under Construction',
        'est_mw': 275,
        'go_live_est': 'Q2 2027',
        'owner': 'Microsoft',
        'customer': 'Microsoft Azure',
        'utility': 'We Energies',
        'sources': 'Microsoft Wisconsin data center announcement',
    },
    {
        'project_id': 'IN-INDIANAPOLIS-001',
        'name': 'Stack Indianapolis',
        'address': 'Indianapolis, IN',
        'city': 'Indianapolis',
        'county': 'Marion',
        'state': 'IN',
        'lat': 39.7684,
        'lon': -86.1581,
        'status': 'Permitting',
        'est_mw': 220,
        'go_live_est': 'Q1 2027',
        'owner': 'Stack Infrastructure',
        'utility': 'AES Indiana',
        'sources': 'Stack Infrastructure development pipeline',
    },
    {
        'project_id': 'TN-NASHVILLE-001',
        'name': 'Google Clarksville Campus',
        'address': 'Clarksville, TN',
        'city': 'Clarksville',
        'county': 'Montgomery',
        'state': 'TN',
        'lat': 36.5298,
        'lon': -87.3595,
        'status': 'Under Construction',
        'est_mw': 400,
        'go_live_est': 'Q3 2026',
        'owner': 'Google',
        'customer': 'Google Cloud',
        'utility': 'Cumberland Electric',
        'sources': 'Google Tennessee investment',
    },
    {
        'project_id': 'AL-HUNTSVILLE-001',
        'name': 'Meta Huntsville',
        'address': 'Huntsville, AL',
        'city': 'Huntsville',
        'county': 'Madison',
        'state': 'AL',
        'lat': 34.7304,
        'lon': -86.5861,
        'status': 'Under Construction',
        'est_mw': 380,
        'go_live_est': 'Q4 2026',
        'owner': 'Meta',
        'utility': 'Huntsville Utilities',
        'epc': 'AECOM Hunt',
        'sources': 'Meta Alabama data center',
    },
    {
        'project_id': 'OK-PRYOR-001',
        'name': 'Google Pryor Campus',
        'address': 'Pryor, OK',
        'city': 'Pryor',
        'county': 'Mayes',
        'state': 'OK',
        'lat': 36.3084,
        'lon': -95.3169,
        'status': 'Live',
        'est_mw': 250,
        'owner': 'Google',
        'customer': 'Google Cloud',
        'utility': 'Grand River Dam Authority',
        'epc': 'Mortenson Construction',
        'electrical_contractor': 'Rosendin Electric',
        'sources': 'Google Oklahoma data center',
    },
    {
        'project_id': 'UT-SALT-LAKE-001',
        'name': 'Switch Pyramid Campus',
        'address': 'West Jordan, UT',
        'city': 'West Jordan',
        'county': 'Salt Lake',
        'state': 'UT',
        'lat': 40.6097,
        'lon': -111.9391,
        'status': 'Under Construction',
        'est_mw': 300,
        'go_live_est': 'Q2 2026',
        'owner': 'Switch',
        'utility': 'Rocky Mountain Power',
        'sources': 'Switch Utah expansion',
    },
    {
        'project_id': 'ID-BOISE-001',
        'name': 'Meta Eagle Mountain',
        'address': 'Kuna, ID',
        'city': 'Kuna',
        'county': 'Ada',
        'state': 'ID',
        'lat': 43.4916,
        'lon': -116.4202,
        'status': 'Under Construction',
        'est_mw': 420,
        'go_live_est': 'Q1 2027',
        'owner': 'Meta',
        'utility': 'Idaho Power',
        'sources': 'Meta Idaho data center announcement',
    },
    {
        'project_id': 'WA-QUINCY-001',
        'name': 'Microsoft Quincy Expansion',
        'address': 'Quincy, WA',
        'city': 'Quincy',
        'county': 'Grant',
        'state': 'WA',
        'lat': 47.2337,
        'lon': -119.8528,
        'status': 'Under Construction',
        'est_mw': 350,
        'go_live_est': 'Q3 2026',
        'owner': 'Microsoft',
        'customer': 'Microsoft Azure',
        'utility': 'Grant County PUD',
        'sources': 'Microsoft Washington data centers',
    },
    {
        'project_id': 'OR-PRINEVILLE-001',
        'name': 'Meta Prineville Campus',
        'address': 'Prineville, OR',
        'city': 'Prineville',
        'county': 'Crook',
        'state': 'OR',
        'lat': 44.2998,
        'lon': -120.8342,
        'status': 'Live',
        'est_mw': 380,
        'owner': 'Meta',
        'utility': 'Pacific Power',
        'epc': 'DPR Construction',
        'electrical_contractor': 'Rosendin Electric',
        'sources': 'Meta Oregon data center',
    },
    {
        'project_id': 'CA-LOS-ANGELES-001',
        'name': 'CoreSite LA3 Expansion',
        'address': 'El Segundo, CA',
        'city': 'El Segundo',
        'county': 'Los Angeles',
        'state': 'CA',
        'lat': 33.9192,
        'lon': -118.4165,
        'status': 'Approved',
        'est_mw': 75,
        'go_live_est': 'Q4 2026',
        'owner': 'CoreSite',
        'utility': 'Southern California Edison',
        'sources': 'CoreSite LA expansion',
    },
    {
        'project_id': 'CA-SANTA-CLARA-001',
        'name': 'Digital Realty SV15',
        'address': 'Santa Clara, CA',
        'city': 'Santa Clara',
        'county': 'Santa Clara',
        'state': 'CA',
        'lat': 37.3541,
        'lon': -121.9552,
        'status': 'Under Construction',
        'est_mw': 120,
        'go_live_est': 'Q1 2026',
        'owner': 'Digital Realty',
        'utility': 'Silicon Valley Power',
        'epc': 'DPR Construction',
        'sources': 'Digital Realty Silicon Valley',
    },
    {
        'project_id': 'NV-LAS-VEGAS-001',
        'name': 'Switch SUPERNAP 10',
        'address': 'Las Vegas, NV',
        'city': 'Las Vegas',
        'county': 'Clark',
        'state': 'NV',
        'lat': 36.1699,
        'lon': -115.1398,
        'status': 'Under Construction',
        'est_mw': 250,
        'go_live_est': 'Q2 2026',
        'owner': 'Switch',
        'utility': 'NV Energy',
        'sources': 'Switch Las Vegas campus',
    },
    {
        'project_id': 'CO-DENVER-001',
        'name': 'Vantage Denver Campus',
        'address': 'Aurora, CO',
        'city': 'Aurora',
        'county': 'Arapahoe',
        'state': 'CO',
        'lat': 39.7294,
        'lon': -104.8319,
        'status': 'Approved',
        'est_mw': 180,
        'go_live_est': 'Q3 2026',
        'owner': 'Vantage Data Centers',
        'utility': 'Xcel Energy',
        'sources': 'Vantage Denver development',
    },
    {
        'project_id': 'NE-OMAHA-001',
        'name': 'Meta Papillion Campus',
        'address': 'Papillion, NE',
        'city': 'Papillion',
        'county': 'Sarpy',
        'state': 'NE',
        'lat': 41.1544,
        'lon': -96.0422,
        'status': 'Under Construction',
        'est_mw': 450,
        'go_live_est': 'Q4 2026',
        'owner': 'Meta',
        'utility': 'Omaha Public Power District',
        'epc': 'Kiewit',
        'sources': 'Meta Nebraska data center',
    },
    {
        'project_id': 'KS-KANSAS-CITY-001',
        'name': 'Google Papillion',
        'address': 'Papillion, NE',
        'city': 'Papillion',
        'county': 'Sarpy',
        'state': 'NE',
        'lat': 41.1644,
        'lon': -96.0522,
        'status': 'Under Construction',
        'est_mw': 300,
        'go_live_est': 'Q1 2027',
        'owner': 'Google',
        'customer': 'Google Cloud',
        'utility': 'Omaha Public Power District',
        'sources': 'Google Nebraska investment',
    },
    {
        'project_id': 'MI-DETROIT-001',
        'name': 'Iron Mountain Detroit',
        'address': 'Southfield, MI',
        'city': 'Southfield',
        'county': 'Oakland',
        'state': 'MI',
        'lat': 42.4734,
        'lon': -83.2219,
        'status': 'Approved',
        'est_mw': 95,
        'go_live_est': 'Q2 2027',
        'owner': 'Iron Mountain',
        'utility': 'DTE Energy',
        'sources': 'Iron Mountain expansion',
    },
    {
        'project_id': 'NY-BUFFALO-001',
        'name': 'NTT Buffalo Data Center',
        'address': 'Buffalo, NY',
        'city': 'Buffalo',
        'county': 'Erie',
        'state': 'NY',
        'lat': 42.8864,
        'lon': -78.8784,
        'status': 'Permitting',
        'est_mw': 140,
        'go_live_est': 'Q4 2026',
        'owner': 'NTT Global Data Centers',
        'utility': 'National Grid',
        'sources': 'NTT New York expansion',
    },
]

def seed_database():
    init_db()
    session = get_session()
    
    # Seed companies
    for comp_data in COMPANIES:
        existing = session.query(Company).filter_by(name=comp_data['name']).first()
        if not existing:
            company = Company(**comp_data)
            session.add(company)
            print(f"Added company: {comp_data['name']}")
    
    session.commit()
    
    # Seed projects
    for proj_data in SEED_PROJECTS:
        existing = session.query(Project).filter_by(project_id=proj_data['project_id']).first()
        if not existing:
            project = Project(**proj_data)
            session.add(project)
            print(f"Added project: {proj_data['name']}")
    
    session.commit()
    print(f"\nSeeded {len(COMPANIES)} companies and {len(SEED_PROJECTS)} projects")
    session.close()

if __name__ == '__main__':
    seed_database()
